export { default as ProfilePage } from './profile/profile';
export { default as DashboardPage } from './dashboard/dashboard';
export { default as ProductManagementPage } from './ProductManagement/ProductManagement';
export { default as CategoryManagementPage } from './CategoryManagement/CategoryManagement';
export { default as OrderManagementPage } from './OrderManagement/OrderManagement';
export { default as CustomerManagementPage } from './CustomerManagement/CustomerManagement';
export { default as ShipmentManagementPage } from './ShipmentManagement/ShipmentManagement';
export { default as SupplierManagementPage } from './SupplierManagement/SupplierManagement';
export { default as WarehouseManagementPage } from './WarehouseManagement/WarehouseManagement';
